### ISSUE TITLE
How to use async in koa-router/koa-route

### ISSUE THREAD

**Issue by txchen** [thenables/composition#4]
Thanks for making this project! Now I can use async function in koa, and it works well.

However if I want to use routing, I found that both koa-router and koa-route cannot support async well, code is like this:

```
app.use(route.get('/somepath', async function() {
  this.body = await someAsyncFunc()
}))
```

and in runtime it would throw error like:

```
TypeError: undefined is not a function
      at Object.dispatch (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa-router/lib/router.js:317:14)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/co/index.js:64:19)
      at /Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/co/index.js:53:5
      at Object.co (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/co/index.js:49:10)
      at Wrap.<anonymous> (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/composition/index.js:48:19)
      at Wrap.Object.defineProperty.get (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/composition/node_modules/memorizer/index.js:5:38)
      at Wrap.then (/Users/txchen/GithubCode/babel-nodeserver/node_modules/koa/node_modules/composition/index.js:94:14)
      at runMicrotasksCallback (node.js:337:7)
      at process._tickCallback (node.js:355:11)
```

I see composition in the callstack, is there a way to workaround this? Thanks!

**Comment by jonathanong** [comment]
each project will have to support it =/

**Comment by txchen** [comment]
I end up using this to workaround

```
router.get('/', function *() {
  yield (async () => {
    this.body = `Hello World: ${utils.magic()} and ${await utils.fooTask()}`
  })()
})
```

**Comment by liranp** [comment]
txchen: How are you dealing with yield next / await next?

**Comment by txchen** [comment]
@liranp I think I don't need to. In side the async function, it is all async/await, I don't need to use yield and generator any more.

**Comment by liranp** [comment]
@txchen: Did you try to do something like await next? I think that it's not working at all...

**Comment by txchen** [comment]
@liranp  No. what's "async next" and "await next"?

**Comment by liranp** [comment]
@txchen await next is supposed to be the equivalent of yield next which pass the control to the next middleware.
